import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

function read(relativePath) {
  return readFileSync(new URL(`../../${relativePath}`, import.meta.url), "utf8");
}

test("shell and workspace layouts favor a wider primary content canvas", () => {
  const shellCss = read("apps/secretary-console/styles.css");
  const meetingsCss = read("apps/secretary-console/views/meetings/meetings.css");
  const businessHubCss = read("apps/secretary-console/views/business-hub/business-hub.css");
  const dashboardCss = read("apps/secretary-console/views/dashboard/dashboard.css");
  const sidebarCss = read("apps/secretary-console/components/sidebar.css");
  const meetingsViewJs = read("apps/secretary-console/views/meetings/meetings-view.js");
  const businessHubViewJs = read("apps/secretary-console/views/business-hub/business-hub-view.js");
  const meetingHeaderJs = read("apps/secretary-console/views/meetings/meeting-detail-header.js");
  const businessDetailJs = read("apps/secretary-console/views/business-hub/business-detail.js");
  const actionItemsTabJs = read("apps/secretary-console/views/meetings/tabs/action-items-tab.js");
  const motionsTabJs = read("apps/secretary-console/views/meetings/tabs/motions-tab.js");
  const reviewsTabJs = read("apps/secretary-console/views/business-hub/tabs/reviews-tab.js");
  const quotesTabJs = read("apps/secretary-console/views/business-hub/tabs/quotes-tab.js");
  const settingsViewJs = read("apps/secretary-console/views/settings/settings-view.js");
  const appJs = read("apps/secretary-console/app.js");
  const adminRouteHandlersJs = read("apps/secretary-console/views/admin/admin-route-handlers.js");
  const dashboardViewJs = read("apps/secretary-console/views/dashboard/dashboard-view.js");
  const stripeAdminHtml = read("apps/secretary-console/stripe-admin.html");
  const productsAdminHtml = read("apps/secretary-console/products-admin.html");

  assert.match(shellCss, /body\s*\{[\s\S]*grid-template-columns:\s*var\(--sidebar-width\)\s+minmax\(0,\s*1fr\);/);
  assert.match(shellCss, /--surface-elevated-start:/);
  assert.match(shellCss, /@media\s*\(prefers-color-scheme:\s*dark\)\s*\{[\s\S]*--surface-elevated-start:/);
  assert.match(shellCss, /\.shell\s*\{[\s\S]*grid-column:\s*2;/);
  assert.doesNotMatch(shellCss, /margin-left:\s*220px;/);
  assert.match(meetingsCss, /grid-template-columns:\s*minmax\(320px,\s*var\(--meetings-list-width,\s*360px\)\)\s+12px\s+minmax\(0,\s*1fr\);/);
  assert.match(businessHubCss, /grid-template-columns:\s*minmax\(320px,\s*var\(--business-list-width,\s*380px\)\)\s+12px\s+minmax\(0,\s*1fr\);/);
  assert.match(meetingsCss, /\.pane-splitter/);
  assert.match(businessHubCss, /\.pane-splitter/);
  assert.match(dashboardCss, /grid-template-columns:\s*repeat\(2,\s*minmax\(0,\s*1fr\)\);/);
  assert.match(dashboardCss, /\.dashboard-lanes-grid\s*\{[\s\S]*grid-template-columns:\s*repeat\(2,\s*minmax\(0,\s*1fr\)\);/);
  assert.match(dashboardCss, /\.dashboard-section-head--actionable/);
  assert.match(dashboardCss, /\.dashboard-section-link/);
  assert.match(dashboardCss, /\.dashboard-city-status/);
  assert.match(dashboardCss, /\.dashboard-city-actions/);
  assert.match(dashboardCss, /\.dashboard-section-link--secondary/);
  assert.match(dashboardCss, /\.dashboard-card-cta/);
  assert.match(dashboardCss, /\.dashboard-stat-card:focus-visible/);
  assert.match(dashboardCss, /\.dashboard-lane-card:focus-visible/);
  assert.match(dashboardCss, /\.dashboard-feature-card:focus-visible/);
  assert.match(dashboardCss, /\.dashboard-calendar-item:focus-visible/);
  assert.match(meetingsCss, /\.detail-summary-grid/);
  assert.match(meetingsCss, /\.detail-tab-bar\s*\{[\s\S]*position:\s*sticky;/);
  assert.match(businessHubCss, /\.business-summary-strip/);
  assert.match(businessHubCss, /\.business-tab-bar\s*\{[\s\S]*position:\s*sticky;/);
  assert.match(businessHubCss, /\.review-card\s*\{[\s\S]*border-radius:\s*16px;/);
  assert.match(businessHubCss, /\.quote-card\s*\{[\s\S]*border-radius:\s*16px;/);
  assert.match(businessHubCss, /\.loading-message,[\s\S]*border-radius:\s*16px;/);
  assert.match(businessHubCss, /linear-gradient\(180deg,\s*var\(--surface-elevated-start\),\s*var\(--surface-elevated-end\)\)/);
  assert.match(dashboardCss, /linear-gradient\(180deg,\s*var\(--surface-elevated-start\),\s*var\(--surface-elevated-end\)\)/);
  assert.match(dashboardCss, /\.dashboard-action:focus-visible/);
  assert.match(dashboardCss, /\.utility-pill\s*\{[\s\S]*border:\s*1px solid/);
  assert.match(sidebarCss, /\.sidebar\s*\{[\s\S]*position:\s*sticky;/);
  assert.doesNotMatch(sidebarCss, /transition:\s*all/);
  assert.match(meetingsCss, /\.btn-icon\s*\{[\s\S]*transition:[\s\S]*background-color 0\.2s ease/);
  assert.match(meetingsCss, /\.btn-icon:focus-visible/);
  assert.match(businessHubCss, /\.btn-row-menu:focus-visible/);
  assert.match(shellCss, /\.admin-workspace-grid/);
  assert.match(shellCss, /\.admin-workspace-frame/);
  assert.match(shellCss, /\.pill\s*\{[\s\S]*font-weight:\s*700;/);
  assert.match(dashboardViewJs, /dashboard-stat-card dashboard-click-card/);
  assert.match(dashboardViewJs, /dashboard-lane-card dashboard-click-card/);
  assert.match(dashboardViewJs, /dashboard-feature-card dashboard-click-card/);
  assert.match(dashboardViewJs, /dashboard-calendar-item dashboard-click-card/);
  assert.match(dashboardViewJs, /dashboard-section-link/);
  assert.match(dashboardViewJs, /dashboard-city-status/);
  assert.match(dashboardViewJs, /dashboard-city-actions/);
  assert.match(dashboardViewJs, /model\.cityFocus\.primaryCta/);
  assert.match(dashboardViewJs, /model\.navigationLinks\.feature/);
  assert.match(meetingsViewJs, /pane-splitter/);
  assert.match(meetingsViewJs, /attachPaneSplitter/);
  assert.match(businessHubViewJs, /pane-splitter/);
  assert.match(businessHubViewJs, /attachPaneSplitter/);
  assert.match(meetingHeaderJs, /detail-summary-grid/);
  assert.match(businessDetailJs, /business-summary-strip/);
  assert.match(actionItemsTabJs, /aria-haspopup="menu"/);
  assert.match(actionItemsTabJs, /aria-expanded="false"/);
  assert.match(motionsTabJs, /aria-haspopup="menu"/);
  assert.match(reviewsTabJs, /aria-expanded="false"/);
  assert.match(quotesTabJs, /aria-haspopup="menu"/);
  assert.match(settingsViewJs, /const settingsContainer = utilityView;/);
  assert.match(appJs, /registerRoute\("\/admin\/stripe"/);
  assert.match(appJs, /registerRoute\("\/admin\/products"/);
  assert.match(appJs, /registerRoute\("\/geo-intelligence"/);
  assert.match(appJs, /geoIntelligenceHandler\(\)/);
  assert.match(appJs, /stripeAdminHandler/);
  assert.match(appJs, /productsAdminHandler/);
  assert.match(adminRouteHandlersJs, /renderAdminWorkspace/);
  assert.match(stripeAdminHtml, /color-scheme:\s*light dark/);
  assert.match(productsAdminHtml, /color-scheme:\s*light dark/);
  assert.match(stripeAdminHtml, /class="tab[^"]*tab-utility-link/);
  assert.doesNotMatch(stripeAdminHtml, /--cam-/);
  assert.match(productsAdminHtml, /--admin-border-strong:/);
  assert.doesNotMatch(productsAdminHtml, /--cam-/);
  assert.match(stripeAdminHtml, /linear-gradient\(180deg,\s*var\(--admin-bg-start\),\s*var\(--admin-bg-end\)\)/);
  assert.match(productsAdminHtml, /linear-gradient\(180deg,\s*var\(--admin-bg-start\),\s*var\(--admin-bg-end\)\)/);
});
